name = "ubq-fi-router"
main = "src/worker.ts"
compatibility_date = "2024-10-01"
minify = true
account_id = "5c0228bee348f4cf48829ffe21b61fe9"

# Note: Routes are managed in Cloudflare dashboard; none declared here.

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
