name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.3.0

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2.4.1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Type check
      run: bun run type-check

    - name: Run comprehensive validation tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bun test tests/comprehensive-validation.test.ts

    - name: Run all other tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bun test --ignore tests/comprehensive-validation.test.ts

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.3.0

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2.4.1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Check build output
      run: |
        echo "Build completed successfully"
        ls -la dist/
        echo "Bundle size:"
        du -h dist/worker.js
