name: Infrastructure Health Check

on:
  schedule:
    # Run every 6 hours to monitor infrastructure
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggers
  push:
    paths:
      - 'tests/comprehensive-validation.test.ts'
      - 'src/**'

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.3.0

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2.4.1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run comprehensive infrastructure validation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bun test tests/comprehensive-validation.test.ts --verbose

    - name: Create issue on infrastructure failure
      if: failure()
      uses: actions/github-script@v7.2.0
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Infrastructure Health Check Failed',
            body: `The scheduled infrastructure health check failed.
            
            **Workflow**: ${{ github.workflow }}
            **Run ID**: ${{ github.run_id }}
            **Timestamp**: ${{ github.event.head_commit.timestamp }}
            
            Please check the workflow logs for details about which services or plugins are failing.
            
            This issue was automatically created by the infrastructure health check workflow.`,
            labels: ['infrastructure', 'automated', 'health-check']
          })
